### ISSUE TITLE
For integration CS-Cart.

### ISSUE THREAD

**Issue by antonioortega** [picqer/magento-extension#1]
Hi, We used magento integration and we wold like to know if there any integration to CS-cart? If not could you recommend someone that could this integration for us?

**Comment by casperbakker** [comment]
Hi Antonio,

We currently do not have a 'native' connection with CS-Cart, and we are not aware of a partner that already built this before.

On our Partners page at https://picqer.com/nl/partners you can find some Dutch business that made plugins for Prestashop and other systems (Pixlabel and eCommerce).

Otherwise you can ask anyone with CS-cart experience to built this for you. Our API is pretty strait forward: https://picqer.com/en/api
